name: GraalVM Native Build

on: [push, pull_request]

permissions:
  contents: write

jobs:
  build_jar:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4.1.7

      - name: Set up JDK
        uses: graalvm/setup-graalvm@v1.2.2
        with:
          java-version: '22'
          distribution: 'graalvm'
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4.3.3
        with:
          name: build-artifact-build_jar
          path: target/*shaded.jar

      - name: Maven Dependency Tree Dependency Submission
        uses: advanced-security/maven-dependency-submission-action@v4.0.3

  build_exe:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4.1.7

      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.0.2

      - name: Visual Studio shell
        uses: egor-tensin/vs-shell@v1

      - name: Set up GraalVM
        uses: gluonhq/setup-graalvm@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - run: java -version

      - name: Build with Maven
        run: mvn -e -Pdesktop gluonfx:build gluonfx:package

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4.3.3
        with:
          name: build-artifact-build_exe
          path: target/gluonfx/x86_64-windows/*.exe
